# Generated by Django 4.0.4 on 2022-06-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_category_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
    ]
