# Generated by Django 4.0.4 on 2022-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_category_movie_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movies.actor'),
        ),
    ]
