# Generated by Django 4.0.4 on 2022-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_actor_remove_movie_actors_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
