# Generated by Django 4.0.4 on 2022-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_actor_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('name',), 'verbose_name': 'Актор', 'verbose_name_plural': 'Актори'},
        ),
        migrations.AddField(
            model_name='actor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
