# Generated by Django 4.0.4 on 2022-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_actor_options_actor_first_name_actor_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(max_length=8, null=True)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
    ]
