# Generated by Django 4.0.4 on 2022-06-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_actornew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actornew',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Актор', 'verbose_name_plural': 'Актори'},
        ),
    ]
