# Generated by Django 4.0.4 on 2022-06-06 19:29

from django.db import migrations


def combine_names(apps, schema_editor):
    Person = apps.get_model('movies', 'Actor')
    for person in Person.objects.all():
        person.first_name,  person.last_name = person.name.split()
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_actornew_options'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
