# Generated by Django 4.0.4 on 2022-06-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20220606_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Актор', 'verbose_name_plural': 'Актори'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name',
        ),
    ]
