# Generated by Django 4.0.4 on 2022-06-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_actor_options_remove_actor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActorNew',
        ),
    ]
