# Generated by Django 4.0.4 on 2022-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_actor_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActorNew',
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
