# Generated by Django 4.0.4 on 2022-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'ordering': ('title', 'title'), 'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
        migrations.AddField(
            model_name='films',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='films',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='actors',
            field=models.CharField(max_length=50, verbose_name='Актори'),
        ),
        migrations.AlterField(
            model_name='films',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категорія'),
        ),
    ]
