# Generated by Django 4.0.4 on 2022-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_films_options_films_time_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Films',
            new_name='Movie',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('time_create', 'title'), 'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
    ]
